### ISSUE TITLE
Add requirements for python

### ISSUE THREAD

**Issue by ansiblejunky** [marlowintexas/ApplePhotoProgram#4]
You don't clearly state the python requirements to run your script. Here's what I needed to make it work:

```
pip install pytz pyicloud
```

**Comment by marlowintexas** [comment]
Thanks for the note.  Ya, this was a play project for a personal need so I
was pretty bad about docs…  my newer version does manage the shared folders
as well now. So, I will try to clean it up in the coming week or so and add
what I can.
