### ISSUE TITLE
Explanation of 'duplicate photo' message

### ISSUE THREAD

**Issue by ansiblejunky** [marlowintexas/ApplePhotoProgram#5]
Can you explain the output of your tool? What's a duplicate photo and how do you determine that? Am I missing a photo that I should be worried about? Just want to be sure. thanks

```
1490 PHOTO FILE(S) DOWNLOADED
6 PHOTO FILE(S) SKIPPED
6 DUPLICATE PHOTO FILE(S) SKIPPED
PROCESS COMPLETED, TOTAL TIME FOR DOWNLOAD PROCESS: 0:18:04.078829
```

**Comment by marlowintexas** [comment]
When I bring the photos down, I create a new file structure based on the
photo date in the requested directory.  So, dir/year/month/day/filename.  I
wanted to do that to create a strong order that I could manually look
through easily.  That is what I validate against being a duplicate.  So if
the name, day, month and year of the file are the same, it would be a
duplicate.

David

**Comment by ansiblejunky** [comment]
Interesting! Why are there dupes in iCloud? What creates that? Are the images themselves the same? I'd be curious to test that out. 

This almost seems like a second post-processing command to run against all downloaded files - to check for dupes regardless of year, month, day, name. This would be good cuz we all take so many photos of the same things.

**Comment by marlowintexas** [comment]
For speed sake, I just did not want to download a file that was already
there.  So that is what is meant by duplicate.  I am not “de-duping”
anything, just saying that you had already downloaded that file to that
same location/folder so I will skip downloading it.

David

**Comment by ansiblejunky** [comment]
Oh, gotcha, so if I had ran your tool a couple times you can determine that file has been already downloaded.  That's useful! thanks for explaining
